[build]
  command = "npm run build"
  publish = "_site"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; img-src 'self' data:; font-src 'self'; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline' 'unsafe-eval' unpkg.com identity.netlify.com; worker-src 'self'; connect-src 'self'"
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1"
    X-Content-Type-Options = "nosniff"
    Permissions-Policy = "interest-cohort=()"
