backend:
  name: git-gateway
  repo: supple-kit/eleventy-supple-starter
  branch: main
publish_mode: editorial_workflow
media_folder: 'src/assets/images/cms/'
public_folder: '/assets'
collections:
  - label: 'Globals'
    name: 'globals'
    files:
      - label: 'Metadata'
        name: 'meta_data'
        delete: false
        file: 'src/_data/metadata.json'
        fields:
          - label: 'Site name'
            name: 'name'
            widget: 'string'
          - label: 'Short site name'
            name: 'shortName'
            widget: 'string'
          - label: 'Site description'
            name: 'description'
            widget: 'string'
          - label: 'Theme color'
            name: 'themeColor'
            widget: 'string'
          - label: 'Background color'
            name: 'backgroundColor'
            widget: 'string'
          - label: 'Your site url'
            name: 'url'
            widget: 'string'
            hint: 'eg. https://your-domain.com, without trailing /'
          - label: 'Genre'
            name: 'genre'
            widget: 'string'
            hint: 'Must be a valid shema.org genre'
          - label: 'Author'
            name: 'author'
            widget: 'object'
            fields:
              - label: 'Your name'
                name: 'name'
                widget: 'string'
              - label: 'E-mail'
                name: 'email'
                widget: 'string'
              - label: 'Twitter handle'
                name: 'twitterHandle'
                widget: 'string'
          - label: 'Publisher'
            name: 'publisher'
            widget: 'object'
            fields:
              - label: 'Publisher name'
                name: 'name'
                widget: 'string'
