backend:
  name: git-gateway
  branch: main
publish_mode: editorial_workflow
media_folder: 'src/assets/images/cms/'
public_folder: '/assets'
collections:
  - label: 'Pages'
    name: 'pages'
    files:
      - label: 'Homepage'
        name: 'home'
        delete: false
        file: 'src/index.md'
        slug: '{{slug}}'
        fields:
          - label: 'Layout'
            name: 'layout'
            widget: 'hidden'
            default: 'home.njk'
          - label: 'Title'
            name: 'title'
            widget: 'string'
          - label: 'Description'
            name: 'description'
            widget: 'string'
          - label: 'Navigation'
            name: 'eleventyNavigation'
            widget: 'object'
            fields:
              - label: 'Navigation label'
                name: 'key'
                widget: 'string'
              - label: 'Order'
                name: 'order'
                widget: 'number'
                default: 0
          - label: 'Body text'
            name: 'body'
            widget: 'markdown'
      - label: '404 page'
        name: 'error_page'
        delete: false
        file: 'src/404.md'
        slug: '{{slug}}'
        fields:
          - label: 'Layout'
            name: 'layout'
            widget: 'hidden'
            default: 'base.njk'
          - label: 'Title'
            name: 'title'
            widget: 'string'
          - label: 'Description'
            name: 'description'
            widget: 'string'
          - label: 'Body text'
            name: 'body'
            widget: 'markdown'
  - label: 'Generic pages'
    name: 'generic_pages'
    folder: 'src/pages'
    slug: '{{slug}}'
    preview_path: 'pages/{{slug}}'
    extension: md
    create: true
    fields:
      - label: 'Layout'
        name: 'layout'
        widget: 'hidden'
        default: 'page.njk'
      - label: 'Permalink Override'
        name: 'permalink'
        widget: 'string'
        hint: 'Pattern: "/your-slug/index.html"'
      - label: 'Title'
        name: 'title'
        widget: 'string'
      - label: 'Description'
        name: 'description'
        widget: 'string'
      - label: 'Navigation'
        name: 'eleventyNavigation'
        widget: 'object'
        fields:
          - label: 'Navigation label'
            name: 'key'
            widget: 'string'
          - label: 'Order'
            name: 'order'
            widget: 'number'
            default: 0
      - label: 'Body text'
        name: 'body'
        widget: 'markdown'
  - label: 'Blog posts'
    name: 'blog_posts'
    folder: 'src/posts'
    slug: '{{slug}}'
    preview_path: 'blog/{{slug}}'
    extension: md
    create: true
    fields:
      - label: 'Layout'
        name: 'layout'
        widget: 'hidden'
        default: 'post.njk'
      - label: 'Permalink Override'
        name: 'permalink'
        widget: 'string'
        hint: 'Pattern: "/blog/your-slug/index.html"'
      - label: 'Title'
        name: 'title'
        widget: 'string'
      - label: 'Description'
        name: 'description'
        widget: 'string'
      - label: 'Publish Date'
        name: 'date'
        widget: 'datetime'
      - label: 'Draft'
        name: 'daft'
        widget: 'boolean'
      - label: 'Tags'
        name: 'tags'
        widget: 'list'
        allow_add: true
      - label: 'Body text'
        name: 'body'
        widget: 'markdown'
  - label: 'Site Settings'
    name: 'globals'
    files:
      - label: 'Metadata'
        name: 'meta_data'
        delete: false
        file: 'src/_data/metadata.json'
        fields:
          - label: 'Site name'
            name: 'name'
            widget: 'string'
          - label: 'Short site name'
            name: 'shortName'
            widget: 'string'
          - label: 'Site description'
            name: 'description'
            widget: 'string'
          - label: 'Theme color'
            name: 'themeColor'
            widget: 'string'
          - label: 'Background color'
            name: 'backgroundColor'
            widget: 'string'
          - label: 'Your site url'
            name: 'url'
            widget: 'string'
            hint: 'eg. https://your-domain.com, without trailing /'
          - label: 'Genre'
            name: 'genre'
            widget: 'string'
            hint: 'Must be a valid shema.org genre'
          - label: 'Author'
            name: 'author'
            widget: 'object'
            fields:
              - label: 'Your name'
                name: 'name'
                widget: 'string'
              - label: 'E-mail'
                name: 'email'
                widget: 'string'
              - label: 'Twitter handle'
                name: 'twitterHandle'
                widget: 'string'
          - label: 'Publisher'
            name: 'publisher'
            widget: 'object'
            fields:
              - label: 'Publisher name'
                name: 'name'
                widget: 'string'
